### PR TITLE
Use django-database-url to allow ppl to use sqlite or other db config

### PR DESCRIPTION
**Pull request by hjwp**
I've been trying to figure out a good way to let people use sqlite in dev if they want to.  I saw you were already using django-database-url for the production settings, and I thought that might be a neat solution:

- users just set the `DATABASE_URL` environment variable
- they can use it to use sqlite, or to tweak the postgres username/password/port etc
- you can specify a default value, so that if people don't set the DATABASE_URL variable, it will still work

I've set the default to postgres, so that it's the same as the old default config you had.  You could consider changing to a sqlite default, which might lower the barrier to entry for new contributors, windows users, ppl who don't have postgres installed?  Up to you.

This change has the effect of getting rid of the `DB_NAME`, `DB_HOST`, `DB_PASSWORD` environment variables however.  If anyone was using them to use non-default postrges config on their laptops, that will break, and they'll need to fix it by setting DATABASE_NAME.  You could conceivably still support the old `DB_NAME` environment vars etc by hacking in the django-database-url default, something like this:

    default='postgres://{user}:{password}@{host}:{port}/{db_name}'.format(
        user=os.getenv('DB_USER', 'postgres',),
        password=os.getenv('DB_PASSWORD', ''),
        #... etc etc

But that starts to feel a bit complicated to me?  Like we're using two sets of different environment variables to do database config?  Having a sensible default and just one way of overriding it feels cleaner, and the django-database-url way seems pretty neat...

Details in the patch!

### CODE REVIEW

**Comment by hjwp** [comment]
oh - one thing I should definitely mention is that I haven't actually tested that the postgres defaults I've set actually work! I don't have postgres on this laptop, and i'm on a train with patchy wifi so can't really install it... So do check that before merging!  :blush:

**Comment by hjwp** [comment]
OK so I've now managed to install postgres and I can confirm that the DATABASE_URL thingie works.

**Comment by hjwp** [comment]
With that said -- I'm starting to think that setting the default config to postgres isn't much help -- basically, if you're using postgres, then you're going to need to drop into a postgres shell create a role and a database for django to use, no matter what.  So having a set of defaults is kinda pointless, because they need to match whatever you do in that shell.

**Comment by hjwp** [comment]
So it seems to me there are three options

1. to use a postgres default database config: set some defaults for database name, database username, database password, and then update the installation instructions to use those defaults, so people can just copy and paste into the postgres shell, and it "just works".

2. remove the default altogether -- now there's no magic, and we continue to explain using placeholders like `<appname>` and `<database_password>` how to do postgres config *and* how to do DATABASE_URL config

3. set the default to being sqlite, so that the application "just works" with no config at all, and then include some instructions which encourage people to use postgres for staging/ci/production, with instructions there.  That's my favourite option, because it provides the lowest barrier to entry to new contributors.

Let me know if you like number 3 and I'll update the instructions.

**Comment by Natim** [comment]
It is the same for every database except for SQLite. Also we are wanting to add some geo search functionality that will not be available with SQLite, this is the reason why we should keep up with Postgresql by default. We could also add some documentation to explain how to setup a postgresql docker to ease the process.

You can have an example here: http://readinglist.readthedocs.org/en/latest/installation.html#using-docker and here: https://github.com/mozilla-services/readinglist/blob/master/docker-compose.yml

**Comment by hjwp** [comment]
(or indeed, if you prefer 1 or 2, let me know and I'll do those)

**Comment by hjwp** [comment]
Would spatialite work?  https://docs.djangoproject.com/en/dev/ref/contrib/gis/install/#spatial-database

**Comment by Natim** [comment]
Apparently yes :+1:

**Comment by hjwp** [comment]
:)  shall we go for the sqlite-default option for now then?  I feel like it would be really nice to minimise required config for a dev setup...

**Comment by Natim** [comment]
Seems like a good idea, let see what @nlhkabu thinks.

**Comment by hjwp** [comment]
if we later decide that postgres is really required, we can remove the sqlite default, but we'll still have the benefit that we're using one environment variable (`DATABASE_URL`) for config, instead of 4 (`DB_NAME` et al).

**Comment by Natim** [comment]
Yes definitely.

**Comment by hjwp** [comment]
ok I'll hold off for now.  if the boss likes the sqlite-by-default option number 3, then I'll update the PR and all the docs :)

**Comment by Natim** [comment]
Cool thanks :)

**Comment by nlhkabu** [comment]
My preference is to use postgres locally for that ol 'develop on what you deploy' thing.
That said I see a benefit in making is easy to get up and running with sqlite.  I suppose this means I prefer option 2 out of those presented because it gives developers the most flexibility. Otherwise, could we set the default configuration for each db and then just have a variable that chooses between the two?

My other concern with sqlite is that I hope (maybe, one day) Connect could be used by other organisations (I spoke to one guy who said he'd like to use it as a cancer support network).  Setting sqlite as the default could erroneously suggest to non Django devs that this is the done thing in production....

**Comment by nlhkabu** [comment]
Whoops - didn't mean to close this, just to comment :)

**Comment by Natim** [comment]
> Setting sqlite as the default could erroneously suggest to non Django devs that this is the done thing in production....

Not if it is described correctly in the documentation.

**Comment by hjwp** [comment]
OK, well tell you what, I have some updates to the PR that include updates to docs (readme + installation.rst) that explicitly say, "you can use sqlite for dev, but we recommend postgres, and postgres is strongly recommended in production, and here are the instructions".  it will also explicitly set postgres as the database type for staging and prod.  let me finish that up and push. it, and see how y'all like it?

**Comment by hjwp** [comment]
I'm only harping on about this because postgres is a pain to get installed (think: instructions, for mac, ubuntu, fedora, and windows?), and even after that it's a pain to create a database (again, different instructions for using `createdb` and getting a `psql` shell with correct perms on mac/windows/linux), and it seems like a lot of barriers to put in front of someone who might have just spotted a small bug, and wants to make a 2-line change to 1 test and 1 view function, and submit a quick PR...

**Comment by hjwp** [comment]
let me know if you're still not completely convinced, and i'll rejigger the PR so that it has a postgres-in-dev default, and just instructions for how to use sqlite if ppl want. you can then merge that, and i'll do a separate PR to change the dev default to sqlite, which you can consider as a separate decision...

**Comment by nlhkabu** [comment]
You've convinced me @hjwp .  I pulled it in and it all looks good - and I didn't have to do too much to keep my postgres :)  So looks like we're all happy! :dancers:

**Pull request merged**
