### PR TITLE
re-introduce explicit requirements.txt, despite the duplication with setup.py

### PR DESCRIPTION
**Pull request by hjwp**
The clever -e . thingie in base.txt wasn't working...

### CODE REVIEW

**Comment by Natim** [comment]
The ``-e`` option is a relative so it was working with the ``make install`` command or using ``pip install -r requirements/dev.txt``

The problem is that we will have an out of sync setup.py if we don't use it to deploy the project.

It is already the case with last pr's

The idea is to use the requirements to pin the version with releases and add dependencies for production and tests but we should keep dependencies up to date as much as possible (not tagged in the setup.py)

**Comment by hjwp** [comment]
Problem was the -e wasn't working. It just errored on mine and Hamish's laptops. We tried tweaking it (-e ..) but couldn't get it to work. Figured duplication was a lesser evil than flakiness for now.What were you thinking we would use setup.py for? Pypi? Or something else                                                                                                                                                                                                                                                                                                                                        --Sent from a mobile, excuse brevity.Harry Percival@hjwp+44 78877 02511                                                                                                                                                                                                                From: Rémy HUBSCHERSent: Friday, 5 June 2015 11:49To: nlhkabu/connectReply To: nlhkabu/connectCc: Harry PercivalSubject: Re: [connect] re-introduce explicit requirements.txt, despite the duplication with setup.py (#14)The -e option is a relative so it was working with the make install command or using pip install -r requirements/dev.txt

The problem is that we will have an out of sync setup.py if we don't use it to deploy the project.

It is already the case with last pr's

The idea is to use the requirements to pin the version with releases and add dependencies for production and tests but we should keep dependencies up to date as much as possible (not tagged in the setup.py)

—Reply to this email directly or view it on GitHub.

**Comment by Natim** [comment]
The basic idea is to make sure the Django project is deployed in the virtualenv path so that you don't need to be in the project root to have it in the pythonpath and that you can use django-admin for instance. It also let you read the version from the package resource and to be able to display the current release without error due to copy paste for instance.

**Comment by hjwp** [comment]
I'm going to have to admit to my own ignorance here and say I didn't really understand any of that. I don't suppose you could explain it with a few worked examples? What doesn't work before, how adding setup.py changes that?And is any of it important enough, if we can't figure out how to get that -e working consi‎stently on any potential contributor's laptop? Having a pip install -r that actually works seems more important than being able to use django-admin.py (which, again, this is doubtless ignorance on my part, but I never use myself, since manage.py works fine?)Another question was that we couldn't figure out how to run the bdd tests under the new folder hierarchy you contributed. It used to be just manage.py test bdd, but we couldn't figure out the new command. Manage.py test connect.tests didn't do it...Any way we do get it working again we should document in a readme somewhere...                                                                                                                                                                                                                                                                                                                                        --Sent from a mobile, excuse brevity.Harry Percival@hjwp+44 78877 02511                                                                                                                                                                                                                From: Rémy HUBSCHERSent: Friday, 5 June 2015 12:04To: nlhkabu/connectReply To: nlhkabu/connectCc: Harry PercivalSubject: Re: [connect] re-introduce explicit requirements.txt, despite the duplication with setup.py (#14)The basic idea is to make sure the Django project is deployed in the virtualenv path so that you don't need to be in the project root to have it in the pythonpath and that you can use django-admin for instance. It also let you read the version from the package resource and to be able to display the current release without error due to copy paste for instance.

—Reply to this email directly or view it on GitHub.

**Comment by Natim** [comment]
Well I was going to fix it but apparently you rolledback ? https://github.com/nlhkabu/connect/commit/d2e089d3a2f8a42255faef211e870b4f010b3520

**Comment by Natim** [comment]
I opened https://github.com/nlhkabu/connect/issues/22 but I think I see from where the problems comes from.

**Pull request merged**
