### PR TITLE
Remove useless params from fields to remove warning in syncdb. (null=…

### PR DESCRIPTION
**Pull request by adrienbrunet**
…True for m2m and a max_length for an integerField)

### CODE REVIEW

**Comment by Natim** [comment]
r+

**Comment by adrienbrunet** [comment]
What does that mean? :crying_cat_face:

**Comment by Natim** [comment]
It means that I review the PR and it looks good to me :+1:

**Comment by adrienbrunet** [comment]
Lazy programmers... They're the best :beer:

**Pull request merged**
